### ISSUE TITLE
Erro ao salvar projeto

### ISSUE THREAD

**Issue by Celina-Magalhaes** [endarthur/os#16]
Olá Arthur,

Comecei a usar o programa em inglês e agora funciona bem. Apareceu, porém, um erro ao salvar o projeto:
Traceback (most recent call last): File "C:\Users\celin\AppData\Local\OpenStereo\pkgs\openstereo\os_base.py", line 1090, in save_project_as_dialog self.save_project(fname) File "C:\Users\celin\AppData\Local\OpenStereo\pkgs\openstereo\os_base.py", line 1159, in save_project item_settings_fname, json.dumps(item.item_settings, indent=2) File "json\__init__.py", line 238, in dumps File "json\encoder.py", line 201, in encode File "json\encoder.py", line 430, in _iterencode File "json\encoder.py", line 404, in _iterencode_dict File "json\encoder.py", line 404, in _iterencode_dict File "json\encoder.py", line 437, in _iterencode File "json\encoder.py", line 180, in default TypeError: Object of type 'ChainMap' is not JSON serializable

Obrigada

**Comment by Celina-Magalhaes** [comment]
Outro erro, dessa vez ao tentar abrir arquivo de linha:
Traceback (most recent call last): File "C:\Users\celin\AppData\Local\OpenStereo\pkgs\openstereo\os_base.py", line 261, in dialog_title=_translate("main", "Import line data"), File "C:\Users\celin\AppData\Local\OpenStereo\pkgs\openstereo\os_base.py", line 496, in import_files self, fname=fname, data_type=data_type, direction=direction File "C:\Users\celin\AppData\Local\OpenStereo\pkgs\openstereo\data_import.py", line 62, in __init__ self.on_file_changed() File "C:\Users\celin\AppData\Local\OpenStereo\pkgs\openstereo\data_import.py", line 215, in on_file_changed self.dialect = self.sniff_dialect() File "C:\Users\celin\AppData\Local\OpenStereo\pkgs\openstereo\data_import.py", line 142, in sniff_dialect self.dialect = self.csv_sniffer.sniff(self.sample) File "csv.py", line 188, in sniff _csv.Error: Could not determine delimiter

**Comment by endarthur** [comment]
Olá Celina,

Quando você instalou o OpenStereo?
O primeiro erro deve desaparecer se você desinstalar e instalar a versão mais recente:
https://github.com/endarthur/os/releases/tag/os-v1.0.33
Você pode me enviar o arquivo que você está tentando abrir, ou uma parte dele ao menos, por email?
pra endarthur@gmail.com
Obrigado mais uma vez!

**Comment by Celina-Magalhaes** [comment]
Oi Arthur,

Acho que instalei na semana passada, não me lembro bem que dia. Vou tentar instalar a nova versão.
Também vou te enviar alguns arquivos por email.

Obrigada novamente!
