### ISSUE TITLE
fix opening project files that contain spreadsheets

### ISSUE THREAD

**Issue by endarthur** [endarthur/os#8]
Traceback (most recent call last): File "C:\Users\endar\AppData\Local\OpenStereo\pkgs\openstereo\os_base.py", line 694, in open_project_dialog self.open_project(fname) File "C:\Users\endar\AppData\Local\OpenStereo\pkgs\openstereo\os_base.py", line 836, in open_project item_data = get_data(item_file, data['kwargs']) File "C:\Users\endar\AppData\Local\OpenStereo\pkgs\openstereo\data_import.py", line 382, in get_data sheet = book.sheet_by_name(kwargs['booksheet']) KeyError: 'booksheet'

**Comment by endarthur** [comment]
Also fix project files for the case of opening the same file twice
